# ruff: noqa: F403,F405
from _real_finding_flow_validation_batch_large_shared import *

@pytest.mark.parametrize(
    (
        "pipeline_id",
        "fixture_path",
        "file_path",
        "line_number",
        "function_name",
        "expected_line",
        "reads_subset",
        "expected_writes_subset",
        "trace_symbol",
        "expected_trace_line",
        "expected_definition_line",
        "expected_definition_kind",
        "expected_caller_lines",
        "expected_language",
    ),
    [
        (
            "69ec5b01",
            "nx_connect/logo/DashboardLogo.tsx",
            "app/(dashboard)/components/Logo/Logo.tsx",
            4,
            "Logo",
            "		const { theme, systemTheme } = useTheme();",
            {"useTheme"},
            set(),
            "useTheme",
            None,
            3,
            "function",
            set(),
            "typescript",
        ),
        (
            "69ec5b01",
            "nx_connect/logo/DashboardLogo.tsx",
            "app/(dashboard)/components/Logo/Logo.tsx",
            5,
            "Logo",
            "		const configData = useConfig();",
            {"useConfig"},
            {"configData"},
            "useConfig",
            None,
            3,
            "function",
            set(),
            "typescript",
        ),
        (
            "69ec5b01",
            "nx_connect/logo/DashboardLogo.tsx",
            "app/(dashboard)/components/Logo/Logo.tsx",
            7,
            "Logo",
            "		const logoPath = currentTheme === 'dark' ? configData.LOGO_DARK : configData.LOGO_LIGHT;",
            {"LOGO_DARK", "LOGO_LIGHT", "configData", "currentTheme"},
            {"logoPath"},
            "configData",
            5,
            3,
            "function",
            set(),
            "typescript",
        ),
        (
            "69ec5b01",
            "nx_connect/logo/DashboardLogo.tsx",
            "app/(dashboard)/components/Logo/Logo.tsx",
            9,
            "Logo",
            "		return logoPath ? `${window.location.origin}/${logoPath}` : '';",
            {"location", "logoPath", "origin", "window"},
            set(),
            "logoPath",
            7,
            3,
            "function",
            set(),
            "typescript",
        ),
        (
            "69ec5b01",
            "nx_connect/organizations/page.tsx",
            "app/(dashboard)/organizations/[id]/page.tsx",
            11,
            "OrganizationDetails",
            "	Object.keys(pd.revenuePastYear).forEach((month: string) => {",
            {"Object", "keys", "pd", "revenuePastYear"},
            set(),
            "pd",
            6,
            5,
            "function",
            set(),
            "typescript",
        ),
        (
            "69ec5b01",
            "nx_connect/organizations/page.tsx",
            "app/(dashboard)/organizations/[id]/page.tsx",
            15,
            "OrganizationDetails",
            "		await axios.get(`channel_partners/${rootChannelPartner?.id}/services/available/`)",
            {"axios", "data", "get", "id", "rootChannelPartner"},
            {"availableServices"},
            "rootChannelPartner",
            7,
            5,
            "function",
            set(),
            "typescript",
        ),
        (
            "69ec5b01",
            "nx_connect/organizations/page.tsx",
            "app/(dashboard)/organizations/[id]/page.tsx",
            17,
            "OrganizationDetails",
            "	pd.revenuePastYear.jan.id += quantity * price;",
            {"jan", "pd", "price", "quantity", "revenuePastYear"},
            {"id"},
            "pd",
            6,
            5,
            "function",
            set(),
            "typescript",
        ),
        (
            "69ec5b01",
            "nx_connect/organizations/page.tsx",
            "app/(dashboard)/organizations/[id]/page.tsx",
            18,
            "OrganizationDetails",
            "	service.numberAddedForEachService += quantity;",
            {"quantity", "service"},
            {"numberAddedForEachService"},
            "service",
            10,
            5,
            "function",
            set(),
            "typescript",
        ),
        (
            "69ec5b01",
            "nx_connect/channel_partner_details/page.tsx",
            "app/(dashboard)/channel-partners/[id]/details/page.tsx",
            4,
            "ChannelPartnerDetails",
            "	const allSubChannelPartners = canSwitchToThisAccount ? await fetchAllSubChannelPartners(params.id) : [];",
            {"canSwitchToThisAccount", "fetchAllSubChannelPartners", "id", "params"},
            {"allSubChannelPartners"},
            "params",
            None,
            3,
            "function",
            set(),
            "typescript",
        ),
        (
            "69ec5b01",
            "nx_connect/channel_partner_details/page.tsx",
            "app/(dashboard)/channel-partners/[id]/details/page.tsx",
            5,
            "ChannelPartnerDetails",
            "	const subCpNames = Object.fromEntries(allSubChannelPartners.map((cp) => [cp.id, cp.name]));",
            {"Object", "allSubChannelPartners", "cp", "fromEntries", "id", "map", "name"},
            {"subCpNames"},
            "allSubChannelPartners",
            4,
            3,
            "function",
            set(),
            "typescript",
        ),
        (
            "69ec5b01",
            "nx_connect/channel_partner_details/page.tsx",
            "app/(dashboard)/channel-partners/[id]/details/page.tsx",
            7,
            "ChannelPartnerDetails",
            "	const allChildOrganizations = canSwitchToThisAccount ? await fetchAllChildOrganizations(params.id) : [];",
            {"canSwitchToThisAccount", "fetchAllChildOrganizations", "id", "params"},
            {"allChildOrganizations"},
            "params",
            None,
            3,
            "function",
            set(),
            "typescript",
        ),
        (
            "69ec5b01",
            "nx_connect/channel_partner_details/page.tsx",
            "app/(dashboard)/channel-partners/[id]/details/page.tsx",
            8,
            "ChannelPartnerDetails",
            "	const orgNames = Object.fromEntries(allChildOrganizations.map((org) => [org.id, org.name]));",
            {"Object", "allChildOrganizations", "fromEntries", "id", "map", "name", "org"},
            {"orgNames"},
            "allChildOrganizations",
            7,
            3,
            "function",
            set(),
            "typescript",
        ),
        (
            "69ec5b01",
            "nx_connect/root_layout/DashboardRootLayoutClient.tsx",
            "app/(dashboard)/layout/RootLayoutClient.tsx",
            1,
            "RootLayoutClient",
            "export default function RootLayoutClient({ children }: { children: ReactNode }) {",
            {"isMenuCollapsed", "setIsMenuCollapsed", "useState"},
            {"RootLayoutClient", "children"},
            "RootLayoutClient",
            None,
            1,
            "function",
            set(),
            "typescript",
        ),
        (
            "69ec5b01",
            "nx_connect/root_layout/DashboardRootLayoutClient.tsx",
            "app/(dashboard)/layout/RootLayoutClient.tsx",
            2,
            "RootLayoutClient",
            "	const [isMenuCollapsed, setIsMenuCollapsed] = useState<boolean>(false);",
            {"useState"},
            {"isMenuCollapsed", "setIsMenuCollapsed"},
            "useState",
            None,
            1,
            "function",
            set(),
            "typescript",
        ),
        (
            "69ec5b01",
            "nx_connect/root_layout/DashboardRootLayoutClient.tsx",
            "app/(dashboard)/layout/RootLayoutClient.tsx",
            3,
            "RootLayoutClient",
            "	return children;",
            {"children"},
            set(),
            "children",
            None,
            1,
            "function",
            set(),
            "typescript",
        ),
        (
            "69ec5b01",
            "nx_connect/root_layout/RootLayoutClient.tsx",
            "app/(external)/layout/RootLayoutClient.tsx",
            4,
            "RootLayoutClient",
            "	const configData = await fetchConfig();",
            {"fetchConfig"},
            {"configData"},
            "fetchConfig",
            None,
            3,
            "function",
            set(),
            "typescript",
        ),
        (
            "69ec5b01",
            "nx_connect/root_layout/RootLayoutClient.tsx",
            "app/(external)/layout/RootLayoutClient.tsx",
            7,
            "loadConfig",
            "		const domain = window.location.hostname;",
            {"hostname", "location", "window"},
            {"domain"},
            "window",
            None,
            6,
            "variable",
            {12},
            "typescript",
        ),
        (
            "69ec5b01",
            "nx_connect/root_layout/RootLayoutClient.tsx",
            "app/(external)/layout/RootLayoutClient.tsx",
            8,
            "loadConfig",
            "		const trackingID = domain.includes('connect.nxgo.io') ? 'G-ZFX72ZBEEX' : configData?.GOOGLE_ANALYTICS_ID;",
            {"GOOGLE_ANALYTICS_ID", "configData", "domain", "includes"},
            {"trackingID"},
            "domain",
            7,
            6,
            "variable",
            {12},
            "typescript",
        ),
        (
            "69ec5b01",
            "nx_connect/root_layout/RootLayoutClient.tsx",
            "app/(external)/layout/RootLayoutClient.tsx",
            11,
            "RootLayoutClient",
            "	clearConfigCache();",
            {"clearConfigCache"},
            set(),
            "clearConfigCache",
            None,
            3,
            "function",
            set(),
            "typescript",
        ),
        (
            "5a36b942",
            "cloud_portal/eslint/new-rule.js",
            "scripts/new-rule.js",
            3,
            "newRuleName",
            "const newRuleName = process.argv[2] && process.argv[2].trim();",
            {"argv", "process", "trim"},
            {"newRuleName"},
            "process",
            None,
            3,
            "variable",
            set(),
            "javascript",
        ),
        (
            "5a36b942",
            "cloud_portal/eslint/new-rule.js",
            "scripts/new-rule.js",
            4,
            "ruleFile",
            "const ruleFile = 'export default \"rule-name\";';",
            set(),
            {"ruleFile"},
            "ruleFile",
            4,
            4,
            "variable",
            set(),
            "javascript",
        ),
        pytest.param(
            "5a36b942",
            "cloud_portal/eslint/new-rule.js",
            "scripts/new-rule.js",
            6,
            "writeFileSync",
            "fs.writeFileSync(`./src/rules/${newRuleName}.ts`, ruleFile.replace(/rule-name/g, newRuleName));",
            {"fs", "newRuleName", "replace", "ruleFile", "writeFileSync"},
            set(),
            "ruleFile",
            4,
            6,
            "function",
            {6},
            "javascript",
            marks=pytest.mark.xfail(
                strict=True,
                reason="real finding flow: find_definition(writeFileSync) does not resolve the top-level JS API call target",
            ),
        ),
    ],
)
def test_real_findings_dashboards_pages_layouts_and_new_rule_batch_should_keep_full_flow(
    monkeypatch,
    pipeline_id,
    fixture_path,
    file_path,
    line_number,
    function_name,
    expected_line,
    reads_subset,
    expected_writes_subset,
    trace_symbol,
    expected_trace_line,
    expected_definition_line,
    expected_definition_kind,
    expected_caller_lines,
    expected_language,
    tmp_path,
):
    source = _fixture_text(fixture_path)
    _write_source_tree(tmp_path, file_path, source)
    monkeypatch.setattr(mcp_server, "_read_source", _stub_read_source(source, Path(file_path).name))
    monkeypatch.setattr(mcp_server, "_resolve_source_dir", lambda _pipeline_id: tmp_path)

    classification = mcp_server.classify_file(pipeline_id, file_path)
    extracted = mcp_server.extract_function(pipeline_id, file_path, line_number)
    imports = mcp_server.find_imports(pipeline_id, file_path)
    decorators = mcp_server.find_decorators(pipeline_id, file_path, line_number)
    identifiers = mcp_server.find_identifiers(pipeline_id, file_path, line_number)
    trace = mcp_server.trace_identifier_backward(pipeline_id, file_path, line_number, trace_symbol)
    callers = mcp_server.find_callers(pipeline_id, file_path, function_name)
    definition = mcp_server.find_definition(pipeline_id, function_name)
    route = mcp_server.find_route_to_function(pipeline_id, function_name)

    assert classification["type"] == "production"
    assert isinstance(imports, list)
    assert decorators == []
    assert extracted["meta"]["code_on_line"] == expected_line
    assert identifiers["language"] == expected_language
    assert reads_subset.issubset(set(identifiers["reads"]))
    assert expected_writes_subset.issubset(set(identifiers["writes"]))
    if expected_trace_line is None:
        assert trace == []
    else:
        assert trace
        assert trace[0]["line"] == expected_trace_line
    if expected_caller_lines:
        assert callers
        assert expected_caller_lines.issubset({item["line"] for item in callers if item["file"] == file_path})
    else:
        assert callers == []
    assert any(
        item["file"] == file_path and item["line"] == expected_definition_line and item["kind"] == expected_definition_kind
        for item in definition
    )
    assert route == []


