# ruff: noqa: F403,F405
from _real_finding_flow_validation_batch_large_shared import *

@pytest.mark.parametrize(
    (
        "pipeline_id",
        "fixture_path",
        "file_path",
        "line_number",
        "function_name",
        "expected_line",
        "reads_subset",
        "expected_writes_subset",
        "trace_symbol",
        "expected_trace_line",
        "expected_definition_line",
        "expected_definition_kind",
        "expected_caller_lines",
        "expected_language",
        "expected_type",
    ),
    [
        (
            "5a36b942",
            "cloud_portal/chatmodes/context-extractor.main.js",
            ".github/chatmodes/modules/context-extractor.js",
            15,
            "main",
            "          gitData = JSON.parse(fs.readFileSync(gitDataInput, 'utf8'));",
            {"JSON", "fs", "gitDataInput", "parse", "readFileSync"},
            {"gitData"},
            "gitDataInput",
            11,
            1,
            "function",
            set(),
            "javascript",
            "production",
        ),
        (
            "5a36b942",
            "cloud_portal/chatmodes/context-extractor.main.js",
            ".github/chatmodes/modules/context-extractor.js",
            31,
            "main",
            "          issueData = JSON.parse(fs.readFileSync(issueDataInput, 'utf8'));",
            {"JSON", "fs", "issueDataInput", "parse", "readFileSync"},
            {"issueData"},
            "issueDataInput",
            27,
            1,
            "function",
            set(),
            "javascript",
            "production",
        ),
        (
            "5a36b942",
            "cloud_portal/chatmodes/context-extractor.main.js",
            ".github/chatmodes/modules/context-extractor.js",
            47,
            "main",
            "          commits = JSON.parse(fs.readFileSync(commitsInput, 'utf8'));",
            {"JSON", "commitsInput", "fs", "parse", "readFileSync"},
            {"commits"},
            "commitsInput",
            43,
            1,
            "function",
            set(),
            "javascript",
            "production",
        ),
        (
            "5a36b942",
            "cloud_portal/chatmodes/context-extractor.main.js",
            ".github/chatmodes/modules/context-extractor.js",
            63,
            "main",
            "          files = JSON.parse(fs.readFileSync(filesInput, 'utf8'));",
            {"JSON", "filesInput", "fs", "parse", "readFileSync"},
            {"files"},
            "filesInput",
            59,
            1,
            "function",
            set(),
            "javascript",
            "production",
        ),
        (
            "5a36b942",
            "cloud_portal/chatmodes/context-extractor.main.js",
            ".github/chatmodes/modules/context-extractor.js",
            79,
            "main",
            "          metaData = JSON.parse(fs.readFileSync(metaDataInput, 'utf8'));",
            {"JSON", "fs", "metaDataInput", "parse", "readFileSync"},
            {"metaData"},
            "metaDataInput",
            75,
            1,
            "function",
            set(),
            "javascript",
            "production",
        ),
        (
            "5a36b942",
            "cloud_portal/chatmodes/template-engine.main.js",
            ".github/chatmodes/modules/template-engine.js",
            5,
            "getTemplateContent",
            "      return fs.readFileSync(templatePath, 'utf8');",
            {"fs", "readFileSync", "templatePath"},
            set(),
            "templatePath",
            3,
            2,
            "function",
            {80},
            "javascript",
            "production",
        ),
        (
            "5a36b942",
            "cloud_portal/chatmodes/template-engine.main.js",
            ".github/chatmodes/modules/template-engine.js",
            46,
            "main",
            "          context = JSON.parse(fs.readFileSync(contextInput, 'utf8'));",
            {"JSON", "contextInput", "fs", "parse", "readFileSync"},
            {"context"},
            "contextInput",
            42,
            32,
            "function",
            set(),
            "javascript",
            "production",
        ),
        pytest.param(
            "5a36b942",
            "cloud_portal/chatmodes/template-engine.main.js",
            ".github/chatmodes/modules/template-engine.js",
            65,
            "main",
            "        result = engine.selectTemplate(scores);",
            {"engine", "scores", "selectTemplate"},
            {"result"},
            "scores",
            62,
            32,
            "function",
            set(),
            "javascript",
            "production",
            marks=pytest.mark.xfail(
                strict=True,
                reason="real finding flow: extract_function expands the select case block instead of keeping the exact engine.selectTemplate(scores) line",
            ),
        ),
        pytest.param(
            "5a36b942",
            "cloud_portal/chatmodes/template-engine.main.js",
            ".github/chatmodes/modules/template-engine.js",
            80,
            "main",
            "        const template = await engine.getTemplateContent(templateName);",
            {"engine", "getTemplateContent", "templateName"},
            {"template"},
            "templateName",
            70,
            32,
            "function",
            set(),
            "javascript",
            "production",
            marks=pytest.mark.xfail(
                strict=True,
                reason="real finding flow: extract_function expands the populate case block instead of keeping the exact getTemplateContent call line",
            ),
        ),
        (
            "5a36b942",
            "cloud_portal/chatmodes/template-engine.main.js",
            ".github/chatmodes/modules/template-engine.js",
            101,
            "main",
            "            const gitContext = JSON.parse(fs.readFileSync(gitContextPath, 'utf8'));",
            {"JSON", "fs", "gitContextPath", "parse", "readFileSync"},
            {"gitContext"},
            "gitContextPath",
            99,
            32,
            "function",
            set(),
            "javascript",
            "production",
        ),
        pytest.param(
            "5a36b942",
            "cloud_portal/chatmodes/git-operations.runCommand.js",
            ".github/chatmodes/modules/git-operations.js",
            18,
            "runCommand",
            "        const result = execSync(command, {",
            {"command", "execSync"},
            {"result"},
            "command",
            2,
            2,
            "function",
            set(),
            "javascript",
            "production",
            marks=pytest.mark.xfail(
                strict=True,
                reason="real finding flow: trace_identifier_backward does not resolve the runCommand parameter binding for execSync(command, ...)",
            ),
        ),
        pytest.param(
            "5a36b942",
            "cloud_portal/uri/uri.service.ts",
            "front_end/libs/services/uri.service.ts",
            4,
            "changePort",
            "            `${window.location.protocol}//${window.location.hostname}:${newPort}/${window.location.hash}`,",
            {"hash", "hostname", "location", "newPort", "protocol", "window"},
            set(),
            "newPort",
            2,
            2,
            "method",
            set(),
            "typescript",
            "production",
            marks=pytest.mark.xfail(
                strict=True,
                reason="real finding flow: changePort template literal loses both backward trace and definition resolution for the enclosing class method",
            ),
        ),
        pytest.param(
            "5a36b942",
            "cloud_portal/utils/authorization.ts",
            "front_end/libs/utils/authorization.ts",
            29,
            "authenticateTwoFactorFactory",
            "                    defer(() => cloudApi.getAllAccountInfo(true))",
            {"cloudApi", "defer", "getAllAccountInfo"},
            set(),
            "cloudApi",
            3,
            1,
            "variable",
            set(),
            "typescript",
            "production",
            marks=pytest.mark.xfail(
                strict=True,
                reason="real finding flow: authenticateTwoFactorFactory callback line loses trace and exported factory definition resolution",
            ),
        ),
        pytest.param(
            "69ec5b01",
            "nx_connect/helpers.ts",
            "app/helpers.ts",
            4,
            "moveToNextFocusableByElementId",
            "            const nextFocusable = document.getElementById(elementId);",
            {"document", "elementId", "getElementById"},
            {"nextFocusable"},
            "elementId",
            1,
            1,
            "variable",
            set(),
            "typescript",
            "production",
            marks=pytest.mark.xfail(
                strict=True,
                reason="real finding flow: exported helper arrow function loses both trace and definition resolution on getElementById(elementId)",
            ),
        ),
        pytest.param(
            "07734951",
            "nx_maps_ui/logger.ts",
            "src/lib/logging/logger.ts",
            8,
            "log",
            "      prefix = `- ${level} ${prefix}`;",
            {"level", "prefix"},
            {"prefix"},
            "level",
            4,
            4,
            "method",
            set(),
            "typescript",
            "production",
            marks=pytest.mark.xfail(
                strict=True,
                reason="real finding flow: logger assignment line loses trace and definition resolution and find_callers pollutes the result with an internal console.log call site",
            ),
        ),
    ],
)
def test_real_findings_chatmodes_helpers_and_services_batch_should_keep_full_flow(
    monkeypatch,
    pipeline_id,
    fixture_path,
    file_path,
    line_number,
    function_name,
    expected_line,
    reads_subset,
    expected_writes_subset,
    trace_symbol,
    expected_trace_line,
    expected_definition_line,
    expected_definition_kind,
    expected_caller_lines,
    expected_language,
    expected_type,
    tmp_path,
):
    source = _fixture_text(fixture_path)
    _write_source_tree(tmp_path, file_path, source)
    monkeypatch.setattr(mcp_server, "_read_source", _stub_read_source(source, Path(file_path).name))
    monkeypatch.setattr(mcp_server, "_resolve_source_dir", lambda _pipeline_id: tmp_path)

    classification = mcp_server.classify_file(pipeline_id, file_path)
    extracted = mcp_server.extract_function(pipeline_id, file_path, line_number)
    imports = mcp_server.find_imports(pipeline_id, file_path)
    decorators = mcp_server.find_decorators(pipeline_id, file_path, line_number)
    identifiers = mcp_server.find_identifiers(pipeline_id, file_path, line_number)
    trace = mcp_server.trace_identifier_backward(pipeline_id, file_path, line_number, trace_symbol)
    callers = mcp_server.find_callers(pipeline_id, file_path, function_name)
    definition = mcp_server.find_definition(pipeline_id, function_name)
    route = mcp_server.find_route_to_function(pipeline_id, function_name)

    assert classification["type"] == expected_type
    assert isinstance(imports, list)
    assert decorators == []
    assert extracted["meta"]["code_on_line"] == expected_line
    assert identifiers["language"] == expected_language
    assert reads_subset.issubset(set(identifiers["reads"]))
    assert expected_writes_subset.issubset(set(identifiers["writes"]))
    assert trace
    assert trace[0]["line"] == expected_trace_line
    if expected_caller_lines:
        assert callers
        assert expected_caller_lines.issubset({item["line"] for item in callers if item["file"] == file_path})
    else:
        assert callers == []
    assert any(
        item["file"] == file_path and item["line"] == expected_definition_line and item["kind"] == expected_definition_kind
        for item in definition
    )
    assert route == []


