- name: Deploy Context Extractor API
  hosts: context_host
  become: true
  tasks:
    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker GPG apt key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        filename: docker

    - name: Install Docker Engine and Compose Plugin
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Ensure docker group exists
      group:
        name: docker
        state: present

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Create app directory
      file:
        path: /opt/context_extractor
        state: directory
        owner: "{{ ansible_user }}"
        group: docker
        mode: '0755'

    - name: Copy all project files
      copy:
        src: files/
        dest: /opt/context_extractor/
        owner: "{{ ansible_user }}"
        group: docker
        mode: '0644'

    - name: Build and start container
      community.docker.docker_compose_v2:
        project_src: /opt/context_extractor/
        pull: always
        state: present
