analyzers:
  - name: cppcheck
    type: simple
    image: sast-cppcheck
    time_class: fast

  - name: devskim
    type: simple
    image: sast-devskim
    time_class: medium

  - name: flawfinder
    type: simple
    image: sast-flawfinder
    time_class: fast

  - name: rats
    type: simple
    image: sast-rat
    time_class: fast

  - name: snyk
    type: simple
    image: sast-snyk
    time_class: medium
    env:
      - SNYK_TOKEN

  - name: codechecker
    type: builder
    image: sast-builder-codechecker
    time_class: slow
    env:
      - COMPILE_COMMANDS_PATH
      - COMPILER_PATH
