# Configuration for connecting to DefectDojo
#
# url    – Base URL of your DefectDojo instance. Do not include a trailing slash.
# token  – API token for authenticating with DefectDojo. You can generate
#          this from your user profile in DefectDojo. Consider using an
#          environment variable in production instead of committing the token.
# verify_ssl – Optional. When set to false, SSL certificate verification
#              will be disabled. Default is true.

defectdojo:
  url: "https://defectdojo.local"
  token: "xxx"
  verify_ssl: true