---
MainSourceFile:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_desktop/src/nx/vms/client/desktop/resource_properties/server/poe/moc_poe_settings_store.cpp'
Diagnostics:
  - DiagnosticName:  cppcoreguidelines-special-member-functions
    DiagnosticMessage:
      Message:         'class ''PoeSettingsStore'' defines a destructor but does not define a copy constructor, a copy assignment operator, a move constructor or a move assignment operator'
      FilePath:        '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_desktop/src/nx/vms/client/desktop/resource_properties/server/poe/../../../../../../../../../../../../vms/client/nx_vms_client_desktop/src/nx/vms/client/desktop/resource_properties/server/poe/poe_settings_store.h'
      FileOffset:      444
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_desktop'
  - DiagnosticName:  cppcoreguidelines-special-member-functions
    DiagnosticMessage:
      Message:         'class ''ViewNodePath'' defines a copy constructor but does not define a destructor, a copy assignment operator, a move constructor or a move assignment operator'
      FilePath:        '/home/misha/nika/nx_open/vms/client/nx_vms_client_desktop/src/nx/vms/client/desktop/node_view/details/node/view_node_path.h'
      FileOffset:      376
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_desktop'
  - DiagnosticName:  cppcoreguidelines-special-member-functions
    DiagnosticMessage:
      Message:         'class ''NodeViewState'' defines a copy constructor, a copy assignment operator, a move constructor and a move assignment operator but does not define a destructor'
      FilePath:        '/home/misha/nika/nx_open/vms/client/nx_vms_client_desktop/src/nx/vms/client/desktop/node_view/details/node_view_state.h'
      FileOffset:      230
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_desktop'
...
