---
MainSourceFile:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_core/src/nx/vms/client/core/analytics/moc_analytics_settings_multi_listener.cpp'
Diagnostics:
  - DiagnosticName:  cppcoreguidelines-special-member-functions
    DiagnosticMessage:
      Message:         'class ''AnalyticsSettingsMultiListener'' defines a destructor but does not define a copy constructor, a copy assignment operator, a move constructor or a move assignment operator'
      FilePath:        '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_core/src/nx/vms/client/core/analytics/../../../../../../../../../../vms/client/nx_vms_client_core/src/nx/vms/client/core/analytics/analytics_settings_multi_listener.h'
      FileOffset:      396
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_core'
  - DiagnosticName:  performance-move-const-arg
    DiagnosticMessage:
      Message:         'std::move of the variable ''keyStd'' of the trivially-copyable type ''std::string_view'' (aka ''basic_string_view<char>'') has no effect; remove std::move()'
      FilePath:        '/home/misha/nika/nx_open/libs/nx_reflect/src/nx/reflect/json/deserializer.h'
      FileOffset:      8291
      Replacements:
        - FilePath:        '/home/misha/nika/nx_open/libs/nx_reflect/src/nx/reflect/json/deserializer.h'
          Offset:          8291
          Length:          10
          ReplacementText: ''
        - FilePath:        '/home/misha/nika/nx_open/libs/nx_reflect/src/nx/reflect/json/deserializer.h'
          Offset:          8307
          Length:          1
          ReplacementText: ''
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_core'
  - DiagnosticName:  bugprone-forwarding-reference-overload
    DiagnosticMessage:
      Message:         constructor accepting a forwarding reference can hide the copy and move constructors
      FilePath:        '/home/misha/nika/nx_open/libs/nx_reflect/src/nx/reflect/type_utils.h'
      FileOffset:      7653
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_core'
  - DiagnosticName:  cppcoreguidelines-special-member-functions
    DiagnosticMessage:
      Message:         'class ''BasicBuffer'' defines a copy constructor, a copy assignment operator, a move constructor and a move assignment operator but does not define a destructor'
      FilePath:        '/home/misha/nika/nx_open/libs/nx_utils/src/nx/utils/buffer.h'
      FileOffset:      674
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_core'
  - DiagnosticName:  cert-dcl58-cpp
    DiagnosticMessage:
      Message:         'modification of ''std'' namespace can result in undefined behavior'
      FilePath:        '/home/misha/nika/nx_open/libs/nx_utils/src/nx/utils/buffer.h'
      FileOffset:      43200
      Replacements:    []
    Notes:
      - Message:         '''std'' namespace opened here'
        FilePath:        '/home/misha/nika/nx_open/libs/nx_utils/src/nx/utils/buffer.h'
        FileOffset:      43158
        Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_core'
  - DiagnosticName:  cppcoreguidelines-special-member-functions
    DiagnosticMessage:
      Message:         'class ''Uuid'' defines a copy constructor, a copy assignment operator, a move constructor and a move assignment operator but does not define a destructor'
      FilePath:        '/home/misha/nika/nx_open/libs/nx_utils/src/nx/utils/uuid.h'
      FileOffset:      427
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_core'
  - DiagnosticName:  performance-noexcept-move-constructor
    DiagnosticMessage:
      Message:         move constructors should be marked noexcept
      FilePath:        '/home/misha/nika/nx_open/vms/libs/nx_vms_common/src/core/resource/shared_resource_pointer.h'
      FileOffset:      3341
      Replacements:
        - FilePath:        '/home/misha/nika/nx_open/vms/libs/nx_vms_common/src/core/resource/shared_resource_pointer.h'
          Offset:          3407
          Length:          0
          ReplacementText: ' noexcept '
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_core'
  - DiagnosticName:  performance-noexcept-move-constructor
    DiagnosticMessage:
      Message:         move assignment operators should be marked noexcept
      FilePath:        '/home/misha/nika/nx_open/vms/libs/nx_vms_common/src/core/resource/shared_resource_pointer.h'
      FileOffset:      3621
      Replacements:
        - FilePath:        '/home/misha/nika/nx_open/vms/libs/nx_vms_common/src/core/resource/shared_resource_pointer.h'
          Offset:          3674
          Length:          0
          ReplacementText: ' noexcept '
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_core'
...
