---
MainSourceFile:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_desktop/src/nx/vms/client/desktop/export/widgets/moc_rapid_review_settings_widget.cpp'
Diagnostics:
  - DiagnosticName:  cppcoreguidelines-special-member-functions
    DiagnosticMessage:
      Message:         'class ''RapidReviewSettingsWidget'' defines a destructor but does not define a copy constructor, a copy assignment operator, a move constructor or a move assignment operator'
      FilePath:        '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_desktop/src/nx/vms/client/desktop/export/widgets/../../../../../../../../../../../vms/client/nx_vms_client_desktop/src/nx/vms/client/desktop/export/widgets/rapid_review_settings_widget.h'
      FileOffset:      308
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_desktop'
...
