---
MainSourceFile:  '/home/misha/nika/nx_open/vms/client/nx_vms_client_desktop/src/nx/vms/client/desktop/resource_properties/server/flux/server_settings_dialog_store.cpp'
Diagnostics:
  - DiagnosticName:  cppcoreguidelines-special-member-functions
    DiagnosticMessage:
      Message:         'class ''ServerSettingsDialogStore'' defines a non-default destructor but does not define a copy constructor, a copy assignment operator, a move constructor or a move assignment operator'
      FilePath:        '/home/misha/nika/nx_open/vms/client/nx_vms_client_desktop/src/nx/vms/client/desktop/resource_properties/server/flux/server_settings_dialog_store.h'
      FileOffset:      391
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_desktop'
  - DiagnosticName:  cppcoreguidelines-special-member-functions
    DiagnosticMessage:
      Message:         'class ''PluginInfoEx'' defines a copy constructor, a copy assignment operator, a move constructor and a move assignment operator but does not define a destructor'
      FilePath:        '/home/misha/nika/nx_open/vms/libs/nx_vms_api/src/nx/vms/api/data/analytics_data.h'
      FileOffset:      8680
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_desktop'
  - DiagnosticName:  performance-noexcept-move-constructor
    DiagnosticMessage:
      Message:         move constructors should be marked noexcept
      FilePath:        '/home/misha/nika/nx_open/vms/libs/nx_vms_common/src/core/resource/shared_resource_pointer.h'
      FileOffset:      3341
      Replacements:
        - FilePath:        '/home/misha/nika/nx_open/vms/libs/nx_vms_common/src/core/resource/shared_resource_pointer.h'
          Offset:          3407
          Length:          0
          ReplacementText: ' noexcept '
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_desktop'
  - DiagnosticName:  performance-noexcept-move-constructor
    DiagnosticMessage:
      Message:         move assignment operators should be marked noexcept
      FilePath:        '/home/misha/nika/nx_open/vms/libs/nx_vms_common/src/core/resource/shared_resource_pointer.h'
      FileOffset:      3621
      Replacements:
        - FilePath:        '/home/misha/nika/nx_open/vms/libs/nx_vms_common/src/core/resource/shared_resource_pointer.h'
          Offset:          3674
          Length:          0
          ReplacementText: ' noexcept '
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_desktop'
...
