---
MainSourceFile:  '/home/misha/nika/nx_open/vms/client/nx_vms_client_desktop/src/nx/vms/client/desktop/export/widgets/text_overlay_settings_widget.cpp'
Diagnostics:
  - DiagnosticName:  cppcoreguidelines-special-member-functions
    DiagnosticMessage:
      Message:         'class ''ColorTheme'' defines a destructor but does not define a copy constructor, a copy assignment operator, a move constructor or a move assignment operator'
      FilePath:        '/home/misha/nika/nx_open/vms/client/nx_vms_client_core/src/nx/vms/client/core/skin/color_theme.h'
      FileOffset:      396
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_desktop'
  - DiagnosticName:  cppcoreguidelines-special-member-functions
    DiagnosticMessage:
      Message:         'class ''FontConfig'' defines a destructor but does not define a copy constructor, a copy assignment operator, a move constructor or a move assignment operator'
      FilePath:        '/home/misha/nika/nx_open/vms/client/nx_vms_client_core/src/nx/vms/client/core/skin/font_config.h'
      FileOffset:      354
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_desktop'
  - DiagnosticName:  cppcoreguidelines-special-member-functions
    DiagnosticMessage:
      Message:         'class ''ColorizedIconDeclaration'' defines a destructor but does not define a copy constructor, a copy assignment operator, a move constructor or a move assignment operator'
      FilePath:        '/home/misha/nika/nx_open/vms/client/nx_vms_client_core/src/nx/vms/client/core/skin/skin.h'
      FileOffset:      683
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_desktop'
  - DiagnosticName:  cppcoreguidelines-special-member-functions
    DiagnosticMessage:
      Message:         'class ''Skin'' defines a destructor but does not define a copy constructor, a copy assignment operator, a move constructor or a move assignment operator'
      FilePath:        '/home/misha/nika/nx_open/vms/client/nx_vms_client_core/src/nx/vms/client/core/skin/skin.h'
      FileOffset:      2525
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_desktop'
  - DiagnosticName:  cppcoreguidelines-special-member-functions
    DiagnosticMessage:
      Message:         'class ''Aligner'' defines a destructor but does not define a copy constructor, a copy assignment operator, a move constructor or a move assignment operator'
      FilePath:        '/home/misha/nika/nx_open/vms/client/nx_vms_client_desktop/src/nx/vms/client/desktop/common/utils/aligner.h'
      FileOffset:      413
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_desktop'
  - DiagnosticName:  cppcoreguidelines-special-member-functions
    DiagnosticMessage:
      Message:         'class ''FileExtensionModel'' defines a destructor but does not define a copy constructor, a copy assignment operator, a move constructor or a move assignment operator'
      FilePath:        '/home/misha/nika/nx_open/vms/client/nx_vms_client_desktop/src/nx/vms/client/desktop/common/utils/filesystem.h'
      FileOffset:      969
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_desktop'
  - DiagnosticName:  cppcoreguidelines-special-member-functions
    DiagnosticMessage:
      Message:         'class ''ExportOverlayPersistentSettings'' defines a default destructor but does not define a copy constructor, a copy assignment operator, a move constructor or a move assignment operator'
      FilePath:        '/home/misha/nika/nx_open/vms/client/nx_vms_client_desktop/src/nx/vms/client/desktop/export/settings/export_media_persistent_settings.h'
      FileOffset:      1082
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_desktop'
  - DiagnosticName:  cppcoreguidelines-special-member-functions
    DiagnosticMessage:
      Message:         'class ''TextOverlaySettingsWidget'' defines a non-default destructor but does not define a copy constructor, a copy assignment operator, a move constructor or a move assignment operator'
      FilePath:        '/home/misha/nika/nx_open/vms/client/nx_vms_client_desktop/src/nx/vms/client/desktop/export/widgets/text_overlay_settings_widget.h'
      FileOffset:      353
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_desktop'
  - DiagnosticName:  performance-noexcept-move-constructor
    DiagnosticMessage:
      Message:         move constructors should be marked noexcept
      FilePath:        '/home/misha/nika/nx_open/vms/libs/nx_vms_common/src/core/resource/shared_resource_pointer.h'
      FileOffset:      3341
      Replacements:
        - FilePath:        '/home/misha/nika/nx_open/vms/libs/nx_vms_common/src/core/resource/shared_resource_pointer.h'
          Offset:          3407
          Length:          0
          ReplacementText: ' noexcept '
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_desktop'
  - DiagnosticName:  performance-noexcept-move-constructor
    DiagnosticMessage:
      Message:         move assignment operators should be marked noexcept
      FilePath:        '/home/misha/nika/nx_open/vms/libs/nx_vms_common/src/core/resource/shared_resource_pointer.h'
      FileOffset:      3621
      Replacements:
        - FilePath:        '/home/misha/nika/nx_open/vms/libs/nx_vms_common/src/core/resource/shared_resource_pointer.h'
          Offset:          3674
          Length:          0
          ReplacementText: ' noexcept '
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_desktop'
  - DiagnosticName:  cppcoreguidelines-special-member-functions
    DiagnosticMessage:
      Message:         'class ''OverlaySettings'' defines a non-default destructor but does not define a copy constructor, a copy assignment operator, a move constructor or a move assignment operator'
      FilePath:        '/home/misha/nika/nx_open/vms/libs/nx_vms_common/src/nx/core/transcoding/filters/transcoding_settings.h'
      FileOffset:      594
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/misha/nika/nx_open/build/vms/client/nx_vms_client_desktop'
...
