[pytest]
testpaths = tests
norecursedirs = tests/fixtures
markers =
    cpp: tests for C/C++ logic
    js: tests for JavaScript logic
    py: tests for Python logic
    java: tests for Java logic
    project_analysis: tests for project-wide code analysis tools
    config_analysis: tests for configuration file analysis tools
